development: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['APP_DATABSE_DEV']%>
  pool: 5
  username: <%= ENV['APP_DATABSE_USERNAME']%>
  password: <%= ENV['APP_DATABSE_PASSWORD']%>
  host: db

test:
  <<: *default
  database: <%= ENV['APP_DATABSE_TEST']%>

